# Generated by Django 3.1.1 on 2020-11-20 23:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enterprise', models.CharField(choices=[('Water', 'Water'), ('Power', 'Power'), ('Waste Water', 'Waste Water')], max_length=100)),
                ('issue_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)])),
                ('series', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-Z]$')])),
                ('bond_type', models.CharField(choices=[('Revenue', 'Revenue'), ('Refunding', 'Refunding')], max_length=100)),
                ('CUSIP', models.CharField(max_length=100)),
                ('avg_mature_rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('official_description', models.CharField(max_length=10000)),
                ('original_description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('project_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('prior_spends', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenBondApp.contractor')),
                ('sdgs', models.ManyToManyField(to='greenBondApp.SDG')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_of_proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('prior_year_spending', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('recent_year_spending', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenBondApp.bond')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenBondApp.project')),
            ],
            options={
                'db_table': 'greenBondApp_bond_projects',
            },
        ),
        migrations.AddField(
            model_name='bond',
            name='projects',
            field=models.ManyToManyField(through='greenBondApp.FinancialInfo', to='greenBondApp.Project'),
        ),
    ]
