# Generated by Django 3.1.1 on 2020-11-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenBondApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='prior_spends',
        ),
    ]
