# Generated by Django 3.1.1 on 2020-11-27 04:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenBondApp', '0004_auto_20201125_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)])),
                ('status', models.CharField(choices=[('Built', 'Built'), ('Upgraded', 'Upgraded'), ('Under Construction', 'Under Construction'), ('Not Started', 'Not Started')], max_length=100)),
                ('household_connections_count', models.PositiveIntegerField()),
                ('people_with_access_to_utilities_count', models.PositiveIntegerField()),
                ('people_benefiting_count', models.PositiveIntegerField()),
                ('water_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('water_catchment', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('ghg_emissions_business_as_usual', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('ghg_emissions_actual_emissions', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenBondApp.project')),
            ],
            options={
                'unique_together': {('year', 'project')},
            },
        ),
    ]
