# Generated by Django 3.1.1 on 2020-12-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenBondApp', '0005_timeseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='enterprise',
            field=models.CharField(choices=[('Water', 'Water'), ('Power', 'Power'), ('Wastewater', 'Wastewater')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='timeseries',
            unique_together=set(),
        ),
    ]
